{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.7/site-packages (2.9.3)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: sqlalchemy-redshift in /opt/conda/lib/python3.7/site-packages (0.8.11)\n",
      "Requirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from sqlalchemy-redshift) (20.1)\n",
      "Requirement already satisfied: SQLAlchemy<2.0.0,>=0.9.2 in /opt/conda/lib/python3.7/site-packages (from sqlalchemy-redshift) (1.3.13)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from packaging->sqlalchemy-redshift) (2.4.6)\n",
      "Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from packaging->sqlalchemy-redshift) (1.14.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pydantic in /opt/conda/lib/python3.7/site-packages (1.10.2)\n",
      "Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.7/site-packages (from pydantic) (4.3.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: reverse_geocoder in /opt/conda/lib/python3.7/site-packages (1.5.1)\n",
      "Requirement already satisfied: numpy>=1.11.0 in /opt/conda/lib/python3.7/site-packages (from reverse_geocoder) (1.21.6)\n",
      "Requirement already satisfied: scipy>=0.17.1 in /opt/conda/lib/python3.7/site-packages (from reverse_geocoder) (1.4.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting catboost==1.1\n",
      "  Downloading catboost-1.1-cp37-none-manylinux1_x86_64.whl (76.8 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m76.8/76.8 MB\u001b[0m \u001b[31m15.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hCollecting graphviz\n",
      "  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m47.0/47.0 kB\u001b[0m \u001b[31m964.8 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: plotly in /opt/conda/lib/python3.7/site-packages (from catboost==1.1) (5.8.2)\n",
      "Requirement already satisfied: matplotlib in /opt/conda/lib/python3.7/site-packages (from catboost==1.1) (3.1.3)\n",
      "Requirement already satisfied: pandas>=0.24.0 in /opt/conda/lib/python3.7/site-packages (from catboost==1.1) (1.3.5)\n",
      "Requirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (from catboost==1.1) (1.4.1)\n",
      "Requirement already satisfied: numpy>=1.16.0 in /opt/conda/lib/python3.7/site-packages (from catboost==1.1) (1.21.6)\n",
      "Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from catboost==1.1) (1.14.0)\n",
      "Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.0->catboost==1.1) (2019.3)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.0->catboost==1.1) (2.8.1)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib->catboost==1.1) (2.4.6)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib->catboost==1.1) (0.10.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib->catboost==1.1) (1.1.0)\n",
      "Requirement already satisfied: tenacity>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from plotly->catboost==1.1) (8.0.1)\n",
      "Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->catboost==1.1) (59.3.0)\n",
      "Installing collected packages: graphviz, catboost\n",
      "Successfully installed catboost-1.1 graphviz-0.20.1\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install psycopg2-binary \n",
    "!pip install sqlalchemy-redshift\n",
    "!pip install pydantic\n",
    "!pip install reverse_geocoder\n",
    "!pip install catboost==1.1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting geopandas\n",
      "  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.0/1.0 MB\u001b[0m \u001b[31m9.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: pandas>=0.25.0 in /opt/conda/lib/python3.7/site-packages (from geopandas) (1.3.5)\n",
      "Collecting pyproj>=2.2.0\n",
      "  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.3/6.3 MB\u001b[0m \u001b[31m26.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m\n",
      "\u001b[?25hCollecting fiona>=1.8\n",
      "  Downloading Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m16.7/16.7 MB\u001b[0m \u001b[31m24.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hCollecting shapely>=1.6\n",
      "  Downloading Shapely-1.8.4-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.0 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.0/2.0 MB\u001b[0m \u001b[31m13.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: attrs>=17 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (21.4.0)\n",
      "Requirement already satisfied: six>=1.7 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (1.14.0)\n",
      "Requirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (2022.6.15)\n",
      "Collecting click-plugins>=1.0\n",
      "  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)\n",
      "Requirement already satisfied: click>=4.0 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (7.0)\n",
      "Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (59.3.0)\n",
      "Collecting cligj>=0.5\n",
      "  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)\n",
      "Collecting munch\n",
      "  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (2.8.1)\n",
      "Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (1.21.6)\n",
      "Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (2019.3)\n",
      "Installing collected packages: shapely, pyproj, munch, cligj, click-plugins, fiona, geopandas\n",
      "Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.21 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1 shapely-1.8.4\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install geopandas "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Looking in indexes: https://orY55nXMEjMZh4MxL2xi:****@pypi.fury.io/syngenta-digital/\n",
      "Collecting common_database\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1P2kIP/common_database-0.2.4-py3-none-any.whl (3.2 kB)\n",
      "Collecting dssat_job\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_8K82l/dssat_job-0.1.51-py3-none-any.whl (5.1 kB)\n",
      "Collecting common_database\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1QadUm/common_database-0.2.3-py3-none-any.whl (3.2 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1yZcYE/common_database-0.2.2-py3-none-any.whl (3.2 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1RmZad/common_database-0.2.1-py3-none-any.whl (3.2 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1PfdZ9/common_database-0.2.0-py3-none-any.whl (3.1 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_d6J19/common_database-0.1.6-py3-none-any.whl (2.3 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_YEeXB/common_database-0.1.5-py3-none-any.whl (2.3 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1pCIsQ/common_database-0.1.4-py3-none-any.whl (2.3 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_7Xyfb/common_database-0.1.3-py3-none-any.whl (2.3 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1miaHl/common_database-0.1.2-py3-none-any.whl (2.3 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_gST6p/common_database-0.1.1-py3-none-any.whl (2.2 kB)\n",
      "  Downloading https://pypi.fury.io/syngenta-digital/-/ver_1edF4U/common_database-0.1.0-py3-none-any.whl (2.2 kB)\n",
      "\u001b[31mERROR: Cannot install common-database==0.1.0, common-database==0.1.1, common-database==0.1.2, common-database==0.1.3, common-database==0.1.4, common-database==0.1.5, common-database==0.1.6, common-database==0.2.0, common-database==0.2.1, common-database==0.2.2, common-database==0.2.3 and common-database==0.2.4 because these package versions have conflicting dependencies.\u001b[0m\u001b[31m\n",
      "\u001b[0m\n",
      "The conflict is caused by:\n",
      "    common-database 0.2.4 depends on pymongo==4.2.0\n",
      "    common-database 0.2.3 depends on pymongo==4.2.0\n",
      "    common-database 0.2.2 depends on pymongo==4.2.0\n",
      "    common-database 0.2.1 depends on pymongo==4.2.0\n",
      "    common-database 0.2.0 depends on pymongo==4.2.0\n",
      "    common-database 0.1.6 depends on pymongo==4.2.0\n",
      "    common-database 0.1.5 depends on pymongo==4.2.0\n",
      "    common-database 0.1.4 depends on pymongo==4.2.0\n",
      "    common-database 0.1.3 depends on pymongo==4.2.0\n",
      "    common-database 0.1.2 depends on pymongo==4.2.0\n",
      "    common-database 0.1.1 depends on pymongo==4.2.0\n",
      "    common-database 0.1.0 depends on pymongo==4.1.1\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts\u001b[0m\u001b[31m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install common_database dssat_job --index-url https://orY55nXMEjMZh4MxL2xi:@pypi.fury.io/syngenta-digital/ --upgrade"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# step 1. getting field data from table\n",
    "!python 1_1_get_fields.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl1_2_get_field_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading data from database\n",
      ">> Reading first data from database\n",
      ">> Reading second data from database\n",
      ">> 0\n",
      ">> 150000\n",
      ">> 150000\n",
      ">> 150000\n",
      ">> 300000\n",
      ">> 150000\n",
      ">> 450000\n",
      ">> 150000\n",
      ">> 600000\n",
      ">> 150000\n",
      ">> 750000\n",
      ">> 150000\n",
      ">> 900000\n",
      ">> 29559\n",
      ">> Reading third data from database\n",
      "All rows: 1136794\n",
      ">> Saving data as csv file\n",
      ">> Uploading data in s3 bucket\n",
      ">> Deleting local files\n"
     ]
    }
   ],
   "source": [
    "!python etl1_3_get_remote_sensing.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# step 2. getting all location for weather, ssurgo and nasa \n",
    "!python etl2_1_get_weather_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl2_2_get_ssurgo_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl2_3_get_nasa_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl3_1_match_weather_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl3_2_match_ssurgo_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"etl3_3_match_nasa_locations.py\", line 96, in <module>\n",
      "    args.field_nasa_locations_file,\n",
      "  File \"etl3_3_match_nasa_locations.py\", line 19, in main\n",
      "    logger = logging.getLogger(__name__)\n",
      "NameError: name 'logging' is not defined\n"
     ]
    }
   ],
   "source": [
    "!python etl3_3_match_nasa_locations.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl4_2_get_ssurgo_data.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl4_1_get_weather_data.py --start 8000 --end 11000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl4_3_get_nasa_data.py --start 8000 --end 10000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">> Uploading data in s3 bucket\n",
      ">> Deleting local files\n"
     ]
    }
   ],
   "source": [
    "!python etl5_get_gdd_stages.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating growth stage file\n"
     ]
    }
   ],
   "source": [
    "!python etl6_2_aggregate_nasa_data.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python etl6_3_aggregate_ssurgo_data.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading formatted geocoded file...\n"
     ]
    }
   ],
   "source": [
    "!python etl7_prepare_data.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "32 ==>> Downloading file 7_final_data.csv from S3\n",
      "35 ==>> Row count: 137976\n",
      "43 ==>> Processing stage: V0\n",
      "45 ==>> Row count: 13865\n",
      "60 ==>> Final row count:(16007, 225)\n",
      "64 ==>> Saving data as csv file\n",
      "67 ==>> Uploading data in s3 bucket\n",
      "70 ==>> Deleting local files\n",
      "43 ==>> Processing stage: VE\n",
      "45 ==>> Row count: 13781\n",
      "60 ==>> Final row count:(16063, 394)\n",
      "64 ==>> Saving data as csv file\n",
      "67 ==>> Uploading data in s3 bucket\n",
      "70 ==>> Deleting local files\n",
      "43 ==>> Processing stage: bin1\n",
      "45 ==>> Row count: 13780\n",
      "60 ==>> Final row count:(16135, 563)\n",
      "64 ==>> Saving data as csv file\n",
      "67 ==>> Uploading data in s3 bucket\n",
      "70 ==>> Deleting local files\n",
      "43 ==>> Processing stage: bin2\n",
      "45 ==>> Row count: 13776\n",
      "60 ==>> Final row count:(16211, 732)\n",
      "64 ==>> Saving data as csv file\n",
      "67 ==>> Uploading data in s3 bucket\n",
      "70 ==>> Deleting local files\n",
      "43 ==>> Processing stage: bin3\n",
      "45 ==>> Row count: 13780\n",
      "60 ==>> Final row count:(16069, 901)\n",
      "64 ==>> Saving data as csv file\n"
     ]
    }
   ],
   "source": [
    "!python etl8_create_stage_data.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "27 ==>> Downloading all_data file  in folder8_stages/R5 from S3\n",
      "30 ==>> Row count: 16490\n",
      "34 ==>> Processing year: 2020\n",
      "38 ==>> Train data: (10056, 1746)\n",
      "39 ==>> Test data: (6434, 1746)\n",
      "41 ==>> Saving data as csv file\n",
      "45 ==>> Uploading data in s3 bucket\n",
      "49 ==>> Deleting local files\n",
      "34 ==>> Processing year: 2016\n",
      "38 ==>> Train data: (14522, 1746)\n",
      "39 ==>> Test data: (1968, 1746)\n",
      "41 ==>> Saving data as csv file\n",
      "45 ==>> Uploading data in s3 bucket\n",
      "49 ==>> Deleting local files\n",
      "34 ==>> Processing year: 2018\n",
      "38 ==>> Train data: (14417, 1746)\n",
      "39 ==>> Test data: (2073, 1746)\n",
      "41 ==>> Saving data as csv file\n",
      "45 ==>> Uploading data in s3 bucket\n",
      "49 ==>> Deleting local files\n",
      "34 ==>> Processing year: 2017\n",
      "38 ==>> Train data: (14864, 1746)\n",
      "39 ==>> Test data: (1626, 1746)\n",
      "41 ==>> Saving data as csv file\n",
      "45 ==>> Uploading data in s3 bucket\n",
      "49 ==>> Deleting local files\n",
      "34 ==>> Processing year: 2019\n",
      "38 ==>> Train data: (12101, 1746)\n",
      "39 ==>> Test data: (4389, 1746)\n",
      "41 ==>> Saving data as csv file\n",
      "45 ==>> Uploading data in s3 bucket\n",
      "49 ==>> Deleting local files\n"
     ]
    }
   ],
   "source": [
    "!python etl9_create_train_test.py --stage-folder '8_stages/R5'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "56 ==>> Unzipping file model/cad-2022-09-29-02-29-54-915/output/model.tar.gz from S3\n",
      "Loading model\n",
      "65 ==>> Downloading all_data file  in foldertest/test.csv from S3\n",
      "68 ==>> Row count: 6230\n",
      "80 ==>> Final mape for test data is 12.891563513310677\n"
     ]
    }
   ],
   "source": [
    "!python 11_test_model.py"
   ]
  }
 ],
 "metadata": {
  "instance_type": "ml.t3.medium",
  "kernelspec": {
   "display_name": "Python 3 (Data Science)",
   "language": "python",
   "name": "python3__SAGEMAKER_INTERNAL__arn:aws:sagemaker:eu-central-1:936697816551:image/datascience-1.0"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
